config/routes.rb
Rails.application.routes.draw do
  resources :build_infos

  root 'welcome#index'

  # Handle webhooks
  post 'webhook/bamboo'
  post 'webhook/pivotal'
  post 'webhook/github'
  post 'webhook/gitlab'

  # Visualisations
  get 'welcome/build'
  get 'welcome/repo_statuses'
end

app/models/build_info.rb
class BuildInfo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/build_infos_controller.rb
class BuildInfosController < ApplicationController
  before_action :set_build_info, only: [:show, :edit, :update, :destroy]

  # GET /build_infos
  # GET /build_infos.json
  def index
    @build_infos = BuildInfo.order(time: :desc)
  end

  # GET /build_infos/1
  # GET /build_infos/1.json
  def show
  end

  # GET /build_infos/new
  def new
    @build_info = BuildInfo.new
  end

  # GET /build_infos/1/edit
  def edit
  end

  # POST /build_infos
  # POST /build_infos.json
  def create
    @build_info = BuildInfo.new(build_info_params)

    respond_to do |format|
      if @build_info.save
        format.html { redirect_to @build_info, notice: 'Build info was successfully created.' }
        format.json { render :show, status: :created, location: @build_info }
      else
        format.html { render :new }
        format.json { render json: @build_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /build_infos/1
  # PATCH/PUT /build_infos/1.json
  def update
    respond_to do |format|
      if @build_info.update(build_info_params)
        format.html { redirect_to @build_info, notice: 'Build info was successfully updated.' }
        format.json { render :show, status: :ok, location: @build_info }
      else
        format.html { render :edit }
        format.json { render json: @build_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /build_infos/1
  # DELETE /build_infos/1.json
  def destroy
    @build_info.destroy
    respond_to do |format|
      format.html { redirect_to build_infos_url, notice: 'Build info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_build_info
    @build_info = BuildInfo.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def build_info_params
    params.require(:build_info).permit(:display, :colour, :time)
  end
end

app/controllers/concerns/bambooable.rb
# Methods for processing posts from Bamboo
module Bambooable
  extend ActiveSupport::Concern

  # prefers application/json
  def bamboo
    puts 'processing incoming bamboo payload'
    json = params[:payload]
    data = JSON.parse(CGI.unescape(json))
    puts 'data has been parsed'

    msg = create_bamboo_message(data)
    notify_slack('', msg)
    puts 'all done'

    update_build_infos(msg[:title], msg[:color])

    head :ok
  end

  def create_bamboo_message(data)
    if data['attachments'][0]['color'] == '#ff0000'
      colour = 'danger'
    elsif data['attachments'][0]['color'] == '#00ff00'
      colour = 'good'
    else
      colour = 'warning'
    end

    text = data['attachments'][0]['fallback'].gsub(/\. See details\./, '')

    {
      title: text,
      fallback: text,
      color: colour
    }
  end

  # at the moment this object is tailored for use with Bamboo notifications
  def update_build_infos(text, colour)
    build_info = BuildInfo.new
    build_info.display = text
    build_info.time = DateTime.now
    build_info.colour = colour

    build_info.save
  end
end

app/controllers/concerns/pivotable.rb
# Methods for processing posts from Pivotal
module Pivotable
  extend ActiveSupport::Concern

  # expects application/json
  def pivotal
    message = params[:message]
    slackbot_shipit_notification if message.include?('accepted this')
    head :ok
  end

  def slackbot_shipit_notification
    notify_slack('Time to ship to production!')
  end
end

app/controllers/webhook_controller.rb
require 'json'
require 'slack-notifier'
require 'github_webhook_service'
require 'gitlab_webhook_service'

class WebhookController < ApplicationController
  include Bambooable
  include Pivotable

  # the concerns are using this method to talk to Slack
  def notify_slack(message, data = '')
    unless ENV['SLACK_WEBHOOK_ENDPOINT'].blank?
      notifier = Slack::Notifier.new(ENV['SLACK_WEBHOOK_ENDPOINT'])
      notifier.ping(message, attachments: [data])
    end
  end

  # expects POST application/json
  def github
    GithubWebhookService.handle_payload(JSON.parse(request.body.read))
    head :ok
  end

  # expects POST application/json
  def gitlab
    GitlabWebhookService.handle_payload(JSON.parse(request.body.read))
    head :ok
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

require 'gitlab_api_service'

class WelcomeController < ApplicationController
  REPOS_TO_CHECK = YAML.safe_load(ENV['REPOS_TO_CHECK']).freeze

  def index
  end

  def build
    # Get any builds from today
    @builds = BuildInfo.where(time: Time.now.all_day).order(time: :desc).limit(5)
  end

  def repo_statuses
    @repo_statuses = REPOS_TO_CHECK.map do |repo_hash|
      details = GitlabApiService.repo_details(repo: repo_hash['name'])
      {
        name: details[0],
        descr: details[1],
        commits: GitlabApiService.branch_compare(repo: repo_hash['name'],
                                                 base: repo_hash['base'],
                                                 head: repo_hash['head'])
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/build_infos_helper.rb
module BuildInfosHelper
end

app/helpers/webhook_helper.rb
module WebhookHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def repo_class_from_commit_array(commits)
    commits.empty? ? 'clean' : 'dirty'
  end
end

app/views/build_infos/_form.html.erb
<%= form_for(@build_info) do |f| %>
  <% if @build_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@build_info.errors.count, "error") %> prohibited this build_info from being saved:</h2>

      <ul>
      <% @build_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :display %><br>
    <%= f.text_area :display %>
  </div>
  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/build_infos/edit.html.erb
<h1>Editing Build Info</h1>

<%= render 'form' %>

<%= link_to 'Show', @build_info %> |
<%= link_to 'Back', build_infos_path %>

app/views/build_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Build Infos (<%= @build_infos.count %>)</h1>

<table>
  <thead>
    <tr>
      <th>Display</th>
      <th>Colour</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @build_infos.each do |build_info| %>
      <tr>
        <td><%= build_info.display %></td>
        <td><%= build_info.colour %></td>
        <td><%= build_info.time %></td>
        <td><%= link_to 'Show', build_info %></td>
        <td><%= link_to 'Edit', edit_build_info_path(build_info) %></td>
        <td><%= link_to 'Destroy', build_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Build info', new_build_info_path %>

app/views/build_infos/new.html.erb
<h1>New Build Info</h1>

<%= render 'form' %>

<%= link_to 'Back', build_infos_path %>

app/views/build_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Display:</strong>
  <%= @build_info.display %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @build_info.colour %>
</p>

<p>
  <strong>Time:</strong>
  <%= @build_info.time %>
</p>

<%= link_to 'Edit', edit_build_info_path(@build_info) %> |
<%= link_to 'Back', build_infos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Digital Builder</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
  <%= csrf_meta_tags %>
  <link type="text/css" rel="stylesheet" href="http://fast.fonts.net/cssapi/b88bad85-b88d-4a23-aa6f-4d4a0469310c.css">
  <link type="text/css" rel="stylesheet" href="http://www.bath.ac.uk/origins/css/bath/apps/apps.css">
  <link rel="apple-touch-icon" sizes="180x180" href=<%= asset_path("apple-touch-icon.png") %>>
  <link rel="icon" type="image/png" sizes="32x32" href=<%= asset_path("favicon-32x32.png") %>>
  <link rel="icon" type="image/png" sizes="16x16" href=<%= asset_path("favicon-16x16.png") %>>
<!-- sticky footer -->
  <style>
<!--
.wrapper {
  min-height: 100%;
  height: auto !important;
  height: 100%;
  margin: 0 auto -78px;
}

footer, .push {
  height: 78px;
}

.wrapper + footer {
  margin-bottom: 0;
  padding: 1.44444rem 0
}

.summary-information.big {
  margin-top: 30px;
}
.summary-information.big h1 {
  font-size: 110px;
  line-height: 115%;
}
.summary-information.big p {
  font-size: 55px;
  line-height: 115%;
}
.item-type, .item-recent-action {
  font-size: 36px;
  line-height: 55px;
}

.repo-list div, .repo-list p,
.repo-list ul, .repo-list li {
  margin: 0;
  padding: 0;
}
.repo-list {
  width: 70%;
  margin: 56px auto;
}
.repo-list .updated-at {
  margin: 10px;
  text-align: right;
}
.repo-list .repo-status {
  padding: 10px;
  margin: 10px;
  border-radius: 5px;
}
.repo-status.dirty {
  background-color: pink;
}
.repo-status.clean {
  background-color: lightgreen;
}
.repo-list .repo-status .commit-list {
  padding: 10px;
  background-color: white;
  border-radius: 5px;
}
.repo-list .commit-list ul {
  margin-left: 15px; /* Enough for bullets to clear wrapping padding */
}
.repo-heading {
  position: relative;
}
.repo-name {
  font-weight: bold;
  font-size: 2em;
  font-family: Consolas,"Courier New",Courier,"Lucida Sans Typewriter","Lucida Typewriter",monospace;
}
.repo-descr {
  display: inline-block;
  position: absolute;
  right: 0;
  bottom: 1px;
}
-->
  </style>
</head>
<body class="webhooks <%= controller_name %> <%= action_name %>">
  <div class="wrapper">
<!-- Header -->
    <header>
      <div class="row">
        <div class="small-24 medium-10 large-6 column">
          <img src="http://www.bath.ac.uk/origins/universal/images/logo/uob-logo-inverse.svg" alt="University of Bath logo">
        </div>
        <div class="small-24 medium-14 large-10 column">
          <span class="app-title">Digital builder</span>
        </div>
      </div>
    </header>
<!-- Main navigation -->
    <nav class="site-nav">
      <div class="row">
        <div class="small-24 column">
          <ul>
            <li class="first active"><a href="http://bamboo.bath.ac.uk/">View build plans</a></li>
            <li class="last"><a href="https://www.pivotaltracker.com/n/projects/1262572">View project in Pivotal</a></li>
          </ul>
        </div>
      </div>
    </nav>
<!-- Content -->
    <main>
      <%= yield %>
    </main>
    <div class="push"></div>
  </div>
<!-- Footer -->
  <footer class="page-footer">
      <div class="row">
        <div class="small-24 large-8 column">
          <p><a href="http://www.bath.ac.uk/corporate-information/copyright/">© University of Bath <%= Date.today.year %></a></p>
        </div>
        <div class="small-24 large-16 column">
          <nav>
            <ul>
              <li><a href="http://www.bath.ac.uk/corporate-information/disclaimer/">Disclaimer</a></li>
              <li><a href="http://www.bath.ac.uk/foi/">Freedom of information</a></li>
              <li><a href="http://www.bath.ac.uk/corporate-information/privacy-and-cookie-policy/">Privacy and cookie policy</a></li>
              <li><a href="http://www.bath.ac.uk/index">A–Z</a></li>
            </ul>
          </nav>
        </div>
      </div>
    </footer>
</body>
</html>

app/views/shared/_no_recent_build.html.erb
<section class="summary-information big">
  <div class="row">
    <div class="small--24 columns">
      <h1>No deploys yet</h1>
      <p class="summary">This page will automatically update when new features are available.</p>
    </div>
  </div>
</section>

app/views/shared/_recent_build.html.erb
<section class="summary-information big">
  <div class="row">
    <div class="small--24 columns">
      <h1>New features available!</h1>
      <p class="summary">Our most recent changes were deployed at <%= @builds.first.time.strftime("%H:%M") %></p>
    </div>
  </div>
</section>
<section>
  <div class="row">
    <div class="small-20 small-offset-2 large-24 large-offset-0 column">
      <table class="content-items">
        <caption>Details of our most recent deployments</caption>
        <thead>
          <tr>
            <th scope="col">Recent deployments</th>
            <th scope="col">Time stamp</th>
          </tr>
        </thead>
        <tbody>

        <% @builds.each do |build| %>
          <tr>
            <td class="item-type"><%= build.display %></td>
            <td class="item-recent-action"><%= build.time.strftime("%H:%M") %></td>
          </tr>
        <% end %>

        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/welcome/build.html.erb
<div id="output">
<% if @builds.count > 0 %>
  <%= render partial: 'shared/recent_build' %>
<% else %>
  <%= render partial: 'shared/no_recent_build' %>
<% end %>
</div>

app/views/welcome/grouped.html.erb
<p id="notice"><%= notice %></p>

<h1>Builds by day</h1>

<%= line_chart @builds.count %>

app/views/welcome/index.html.erb
<div id="output">
</div>

<%= javascript_tag do %>
$(function() {

  // milliseconds
  var pollTime = 5000;
  setInterval(function() {
    $('#output').load('/welcome/build #output');
  }, pollTime);

});
<% end %>

app/views/welcome/repo_statuses.html.erb
<div class='repo-list'>
  <div class="updated-at">Updated at: <%= Time.current.in_time_zone.strftime('%Y-%m-%d %H:%M:%S %Z') %></div>
  <% @repo_statuses.each do |repo_status| %>
    <div class="repo-status <%= repo_class_from_commit_array(repo_status[:commits]) %>">
      <p class="repo-heading"><span class='repo-name'><%= repo_status[:name] %></span> <span class='repo-descr'><%= repo_status[:descr] %></span></p>
      <% if repo_status[:commits].present? %>
        <div class="commit-list">
          <ul>
            <% repo_status[:commits].each do |msg| %>
              <li><%= raw msg.gsub(/\n+/, '<br>') %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  <% end %>
</div>